smartquark:
  name: SmartQuark Java Edition
  version: 0.0.1
quarkus:
  application:
    name: ${smartquark.name}
    version: ${smartquark.version}
  banner:
    path: banner.txt
  console:
    color: true
  datasource:
    db-kind: postgresql
  log:
    level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n"
      level: DEBUG